services:
  dota_db:
    image: postgres:14-alpine
  container_name: dota_db
  environment:
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASS}
  volumes:
    - ./sql:/docker-entrypoint-initdb.d
    - pgdata:/var/lib/postgresql/data
  ports:
    - "${DB_PORT}:5432"
  env_file:
    - .env

volumes:
  pgdata:
